### ISSUE TITLE
Create the Place action decision for Storing Groceries task

### ISSUE THREAD

**Issue by Baggiio** [robofeiathome/detector_2d#16]
### Problem Statement:

Currently, our Storing Groceries task does not distinguish the objects on the place table (by category or likeliness), which is strictly necessary to complete the 2023 RoboCup's Storing Groceries Task.

### Proposed Solution:

In order to achieve the task's objective, it's necessary that Hera knows which is the object that she is holding before the place action. Furthermore, Hera needs to recognize every object on the place table, separate them into categories and choose a proper place location for each category.

### Implementation Steps:

- [x] Save which object Hera has picked
- [x] Recognize every object and save their coordinates when Hera arrives the place table
- [ ] Categorize these objects in categories
- [ ] Choose a proper place location for each category
